version: 2

models:
  - name: dim_views
    description: Page views by day
    columns:
      - name: event_date
        description: Date of the event
        tests:
          - unique
          - not_null
      - name: total_page_views
        description: Total number of page views
        tests:
          - not_null
      - name: unique_users
        description: Number of unique users
        tests:
          - not_null

  - name: fct_purchases
    description: |
      Transaction-level fact table with purchase details.
      Note: Filtered to only include complete records (is_complete = TRUE).
    columns:
      - name: transaction_id
        description: Transaction identifier (may have multiple items per transaction)
        tests:
          - not_null
      - name: user_pseudo_id
        description: User identifier
        tests:
          - not_null
      - name: purchase_ts
        description: Purchase timestamp
        tests:
          - not_null
      - name: total_revenue
        description: Total transaction revenue (may be null for some transactions)

  - name: dim_products
    description: |
      Product dimension table with unique products.
      Note: Same product_key may appear with different item details in source data.
    columns:
      - name: product_key
        description: Product identifier
        tests:
          - not_null
      - name: item_name
        description: Product name

  - name: agg_daily_product_revenue
    description: Daily product performance metrics
    columns:
      - name: event_date
        description: Date of the event
        tests:
          - not_null
      - name: product_key
        description: Product identifier
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue for the product on this day

  - name: agg_daily_funnel_long
    description: Long-format funnel metrics for visualization
    columns:
      - name: session_date
        description: Date of the session
        tests:
          - not_null
      - name: stage_order
        description: The numeric order of the funnel stage
        tests:
          - not_null
      - name: stage
        description: The name of the funnel stage
        tests:
          - not_null
      - name: sessions
        description: Number of sessions at this stage
        tests:
          - not_null

  - name: agg_daily_sessions
    description: Daily session metrics aggregated by platform and operating system
    columns:
      - name: session_date
        description: Date of the session
        tests:
          - not_null
      - name: platform
        description: Device platform
        tests:
          - not_null
      - name: operating_system
        description: Device operating system
        tests:
          - not_null
      - name: browser
        description: Web browser
      - name: device_category
        description: Device category (mobile, desktop, tablet)