version: 2

models:
  - name: dim_views
    description: Page views by day
    columns:
      - name: event_date
        description: Date of the event
        tests:
          - unique
          - not_null
      - name: total_page_views
        description: Total number of page views
        tests:
          - not_null
      - name: unique_users
        description: Number of unique users
        tests:
          - not_null

  - name: fct_purchases
    description: |
      Transaction-level fact table with purchase details.
      Note: Filtered to only include complete records (is_complete = TRUE).
    columns:
      - name: transaction_id
        description: Transaction identifier (may have multiple items per transaction)
        tests:
          - not_null
      - name: user_pseudo_id
        description: User identifier
        tests:
          - not_null
      - name: purchase_ts
        description: Purchase timestamp
        tests:
          - not_null
      - name: total_revenue
        description: Total transaction revenue (may be null for some transactions)

  - name: dim_products
    description: |
      Product dimension table with unique products.
      Note: Same product_key may appear with different item details in source data.
    columns:
      - name: product_key
        description: Product identifier
        tests:
          - not_null
      - name: item_name
        description: Product name

  - name: agg_daily_product_revenue
    description: Daily product performance metrics
    columns:
      - name: event_date
        description: Date of the event
        tests:
          - not_null
      - name: product_key
        description: Product identifier
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue for the product on this day

  - name: agg_daily_funnel_long
    description: Long-format funnel metrics for visualization
    columns:
      - name: session_date
        description: Date of the session
        tests:
          - not_null
      - name: stage_order
        description: The numeric order of the funnel stage
        tests:
          - not_null
      - name: stage
        description: The name of the funnel stage
        tests:
          - not_null
      - name: sessions
        description: Number of sessions at this stage
        tests:
          - not_null

  - name: agg_daily_sessions
    description: Daily session metrics aggregated by platform and operating system
    columns:
      - name: session_date
        description: Date of the session
        tests:
          - not_null
      - name: platform
        description: Device platform
        tests:
          - not_null
      - name: operating_system
        description: Device operating system
        tests:
          - not_null
      - name: browser
        description: Web browser
      - name: device_category
        description: Device category (mobile, desktop, tablet)

  - name: rpt_landing_page_performance
    description: |
      Landing page performance analysis showing conversion rates, 
      revenue metrics, and engagement by landing page.
    columns:
      - name: landing_page
        description: URL of the first page viewed in the session
        tests:
          - not_null
      - name: total_sessions
        description: Total number of sessions starting from this landing page
        tests:
          - not_null
      - name: conversion_rate_pct
        description: Percentage of sessions that resulted in a purchase
      - name: total_revenue
        description: Total revenue generated from sessions starting on this page
      - name: avg_session_duration_minutes
        description: Average time spent on site from this landing page

  - name: rpt_session_duration_cohorts
    description: |
      Session duration cohort analysis grouping sessions by time spent
      to show correlation between engagement and conversion.
    columns:
      - name: duration_cohort
        description: Time-spent bucket (e.g., "1-10s", "1-3min")
        tests:
          - not_null
      - name: cohort_order
        description: Numeric order for sorting cohorts
        tests:
          - not_null
      - name: total_sessions
        description: Number of sessions in this duration cohort
        tests:
          - not_null
      - name: conversion_rate_pct
        description: Percentage of sessions that converted
      - name: avg_duration_seconds
        description: Average session duration within this cohort

  - name: rpt_landing_page_engagement_matrix
    description: |
      Cross-analysis of landing pages and engagement levels
      to identify high-performing entry points.
    columns:
      - name: landing_page
        description: URL of the first page viewed in the session
        tests:
          - not_null
      - name: engagement_level
        description: Engagement category (Low/Medium/High)
        tests:
          - not_null
      - name: sessions
        description: Number of sessions in this landing page × engagement combination
        tests:
          - not_null
      - name: conversion_rate_pct
        description: Conversion rate for this combination